
import Redis from "ioredis";
import { v4 as uuidv4 } from "uuid";
import config from "../../../config/config";

const redis = new Redis(config.REDIS_URL, {
  family: 4, //ipv4
});

// A simplified store specifically for OPAQUE
export interface OpaqueSessionData {
  id: string; // User ID
  username: string;
  serverLoginState: string; // The state generated by OPAQUE
}

// (Update your Redis/Memory store methods to save and retrieve this interface)

export const OpaqueSessionStore = {
  save: async (data: OpaqueSessionData): Promise<string> => {
    const sessionId = uuidv4();
    await redis.set(`opaque_login:${sessionId}`, JSON.stringify(data), "EX", 120);
    return sessionId;
  },

  get: async (sessionId: string): Promise<OpaqueSessionData | null> => {
    const data = await redis.get(`opaque_login:${sessionId}`);
    return data ? JSON.parse(data) : null;
  },

  delete: async (sessionId: string) => {
    await redis.del(`opaque_login:${sessionId}`);
  }
};

